# Generated by Django 4.2.7 on 2023-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autor_noticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='anoPublicacao',
            new_name='ano',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='titulo',
            field=models.TextField(default='título do livro', max_length=90),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(choices=[('atica', 'Ática'), ('objetiva', 'Objetiva'), ('atlas', 'Atlas'), ('ftd', 'FTD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ilustrador',
            field=models.CharField(max_length=70, verbose_name='Ilustrador'),
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
