# Generated by Django 4.2.7 on 2023-11-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_livro_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(choices=[('Ática', 'Ática'), ('Objetiva', 'Objetiva'), ('Atlas', 'Atlas'), ('FTD', 'FTD')], max_length=20),
        ),
    ]
