# Generated by Django 4.2.7 on 2023-11-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_livro_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='escritor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.autor', verbose_name='Autor'),
        ),
    ]
